USE TRADER

SELECT P.CODIGO_NEGOCIACAO, CONVERT(DATE, C.DATA_NEGOCIACAO) 'DATA', 
C.VALOR_ABERTURA, C.VALOR_FECHAMENTO, 
--C.VALOR_FECHAMENTO - C.VALOR_ABERTURA 'DIFERENCA', ROUND((((C.VALOR_FECHAMENTO - C.VALOR_ABERTURA)/C.VALOR_ABERTURA)*100),2) '%',
C.QUANTIDADE_NEGOCIOS, C.VALOR_MAXIMO, C.VALOR_MINIMO
FROM TB_PAPEL P 
INNER JOIN TB_COTACAO C ON C.CODIGO_NEGOCIACAO = P.CODIGO_NEGOCIACAO
WHERE P.CODIGO_NEGOCIACAO = 'TRPL4' AND YEAR(C.DATA_NEGOCIACAO) = 2019
ORDER BY C.DATA_NEGOCIACAO DESC