USE Trader

SELECT 
	B.CODIGO_BDI 'BdiCode', 
	B.DESCRICAO_BDI 'BdiDescription',
	P.CODIGO_NEGOCIACAO 'Code',
	M.CODIGO_MERCADO 'MarketCode', 
	M.DESCRICAO_MERCADO 'MarketDescription', 
	P.EMPRESA 'Company',
	E.CODIGO_ESPECIFICACAO 'SpecificationCode', 
	E.DESCRICAO_ESPECIFICACAO 'SpecificationDescription',  
	P.MOEDA 'Currency',
	P.CODIGO_INDICADOR_CORRECAO,
	I.CODIGO_INDICADOR_CORRECAO 'CorrectionIndicatorCode',
	I.SIGLA_INDICADOR_CORRECAO 'CorrectionIndicatorSymbol',
	I.DESCRICAO_INDICADOR_CORRECAO 'CorrectionIndicatorDescription',
	P.FATOR_COTACAO 'CotationFactor',
	P.ISIN 'IsinCode'
FROM 
	TB_PAPEL P WITH(NOLOCK)
	INNER JOIN TB_MERCADO M WITH(NOLOCK) ON P.CODIGO_MERCADO = M.CODIGO_MERCADO
	INNER JOIN TB_BDI B WITH(NOLOCK) ON P.CODIGO_BDI = B.CODIGO_BDI
	INNER JOIN TB_ESPECIFICACAO E WITH(NOLOCK) ON P.CODIGO_ESPECIFICACAO = E.CODIGO_ESPECIFICACAO
	LEFT JOIN TB_INDICADOR_CORRECAO I WITH(NOLOCK) ON P.CODIGO_INDICADOR_CORRECAO = I.CODIGO_INDICADOR_CORRECAO
WHERE 
	--M.CODIGO_MERCADO = 10
	B.CODIGO_BDI = '02'
	--B.CODIGO_BDI = '12'
ORDER BY 
	P.CODIGO_NEGOCIACAO



