USE Trader

--SELECT * FROM TB_PAPEL WITH(NOLOCK) ORDER BY CODIGO_NEGOCIACAO

SELECT * FROM TB_COTACAO WITH(NOLOCK) 
WHERE CODIGO_NEGOCIACAO = 'PETR4'
--AND DATA_NEGOCIACAO <= CONVERT(DATE,'2018-01-01')
ORDER BY DATA_NEGOCIACAO DESC

/*
SELECT * FROM TB_BDI
SELECT * FROM TB_MERCADO
SELECT * FROM TB_ESPECIFICACAO
SELECT * FROM TB_INDICADOR_CORRECAO
*/